### PR TITLE
Update README.md with 1.3.x

### PR DESCRIPTION
**Pull request by genuinefafa**
Refers to #81

### CODE REVIEW

**Comment by witoldsz** [comment]
Whatman about 1.4.x? Should work as well, I guess.

**Comment by genuinefafa** [comment]
What about now? @witoldsz

**Comment by witoldsz** [comment]
What about version 1.4? At the end, can you just squash all the commits? Thanks :-)

**Comment by genuinefafa** [comment]
What about now? Check #106

**Comment by witoldsz** [comment]
Moved to #106

**Pull request closed without merging**
