### PR TITLE
Grunt uglification

### PR DESCRIPTION
**Pull request by spengilley**
Minified js file

This has been tested and works great!

### CODE REVIEW

**Comment by simison** [comment]
Actually, I don't think bower modules should be serving minified files at all. See e.g.:
- https://groups.google.com/d/msg/twitter-bower/P8TbooJPacs/dE5OdIGVEkQJ
- https://github.com/bower/bower/issues/368

**Comment by spengilley** [comment]
This is the only project I am currently using that doesn't have one. You're right though, I could uglify the code myself but this project is the odd one out currently and I wanted to bring it up to scratch in this regard with projects such as query and angularjs itself

**Comment by simison** [comment]
Yup, I'm not very invested in this opinion and a pragmatic way could indeed be adding minified file.

@witoldsz thoughts?

**Comment by witoldsz** [comment]
The idea seems really stupid, the minified version should be present in NPM Repositories, not the source code. The only problem is with Bower which I wish was never adopted by the community.

I have stopped using Bower long time ago, but I am not the only one here, so OK, the minified version will enter the Git "source" code repository. Just one question no one answered me yet: how often should we smudge the repo with updated minified file: on each commit/pull-request, on each release?

**Comment by simison** [comment]
>on each commit/pull-request, on each release?

Release.

**Comment by witoldsz** [comment]
Thanks @simison, just found your other answer to this a while ago :)
Will try to merge, build and release a new version today/tomorrow.

**Comment by spengilley** [comment]
Thanks guys :)

**Pull request merged**
